config/routes.rb
Rails.application.routes.draw do
  get 'feed' => 'epicenter#feed'

  get 'show_user' => 'epicenter#show_user'

  get 'now_following' => 'epicenter#now_following'

  get 'unfollow' => 'epicenter#unfollow'

  get 'tag_tweets' => 'epicenter#tag_tweets'

  get 'all_users' => 'epicenter#all_users'

  get 'following' => 'epicenter#following'

  get 'followers' => 'epicenter#followers'

  resources :tweets
  devise_for :users

  # root 'tweets#index'
  root 'epicenter#feed'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tweet_tags
  has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  has_many :tweet_tags
  has_many :tweets, through: :tweet_tags

  before_validation :link_check, on: :create

  validates :message, presence: true, length: { maximum: 140, too_long: "A tweet is only 140 characters max." }, on: :create

  after_validation :apply_link, on: :create

  private

  def link_check
    if self.message.include?("http://")
      array = self.message.split

      index = array.map { |word| word.include? "http://" }.index(true)

      self.link = array[index]

      if array[index].length > 23
        array[index] = "#{array[index][0..20]}..."
      end

      self.message = array.join(" ")
    end

  end

  def apply_link
    array = self.message.split

    index = array.map { |word| word.include? "http://" }.index(true)
    url = array[index] unless index.nil?

    unless index.nil?
      array[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
    end
    self.message = array.join(" ")
  end
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  serialize :following, Array

  validates :username, presence: true, uniqueness: true

  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :avatar, :following])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :avatar, :following])
  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController

  before_action :authenticate_user!

  def tag_tweets
    @tag = Tag.find(params[:id])
  end

  def feed
    @following_tweets = []

    Tweet.all.order(created_at: :desc).each do |tweet|
      if current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id
        @following_tweets.push(tweet)
      end
    end
  end

  def all_users
    @users = User.all
  end

  def show_user
    @user = User.find(params[:id])
  end

  def following
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if @user.following.include?('id' => user.id.to_s)
        @users.push(user)
      end
    end
  end

  def followers
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if user.following.include?('id' => @user.id.to_s)
        @users.push(user)
      end
    end
  end

  def now_following
    current_user.following.push(id: params[:id])
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  def unfollow
    current_user.following.delete('id' => params[:id])
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  include TweetsHelper

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)

    @tweet = get_tagged(@tweet)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

  def get_tagged(tweet)

    message_array = tweet.message.split

    message_array.each_with_index do |word, index|
      if word[0] == "#"
        # see if the tag exists
        if Tag.pluck(:phrase).include?(word)
          # attach the tweet to existing tag (save it as a variable for when we create the tweet)
          tag = Tag.find_by(phrase: word)
        else
          # otherwise make a tag
          tag = Tag.create(phrase: word)
        end

        tweet_tag = TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)

        message_array[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"

      end
    end

    tweet.update(message: message_array.join(" "))

    tweet

  end

end

app/views/epicenter/_user_list.html.erb
<div class="container-fluid">
  <div class="row">
    <% @users.each do |user| %>
      <div class="col-md-3">
        <div class="well user-list-wells">
          <div class="row">
            <div class="col-md-6">
              <% if user.avatar.url %>
                <%= image_tag user.avatar.url, class: 'user-pic-md img-responsive' %>
              <% end %>
            </div>
            <div class="col-md-6">
              <p>
                <% if current_user.following.include?("id" => user.id.to_s) %>
                  <%= link_to 'Following', unfollow_path(id: user.id), class: 'btn btn-primary', id: 'unfollow_btn' %>
                <% else %>
                  <% if current_user.id != user.id %>
                    <%= link_to 'Follow', now_following_path(id: user.id), class: 'btn btn-primary' %>
                  <% end %>
                <% end %>
              </p>
            </div>
          </div>

          <div class="row">
            <%= link_to show_user_path(id: user.id) do %>
              <h3><%= user.name %></h3>
              <p>@<%= user.username %></p>
            <% end %>
            <p>
              <%= user.bio %>
            </p>
          </div>

        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/epicenter/all_users.html.erb
<h2 class="text-center">All Users</h2>

<%= render 'user_list' %>

app/views/epicenter/feed.html.erb
  <div class="text-center">
    <h1><%= current_user.username %>'s Twitter Feed</h1>
      <div style="text-align: center;">

        <p>Name: <%= current_user.name %></p>

        <% if !current_user.location.empty? %>
          <p>Location: <%= current_user.location %></p>
        <% end %>

        <% if !current_user.bio.empty? %>
          <p>Bio: <%= current_user.bio %></p>
        <% end %>
      </div>

    <!-- <p>Number of Tweets: <%#= Tweet.all.where(:user_id => current_user.id).count %></p> -->
    <!-- <p>Number of Users Following: <%#= User.find_by_id(current_user.id).following.count %></p> -->
    <button class="btn btn-info" type="button">Tweets <span class="badge"><%= Tweet.all.where(:user_id => current_user.id).count %></span></button>
    <!-- <a href="#">Tweets <span class="badge"><%#= Tweet.all.where(:user_id => current_user.id).count %></span></a> -->
    <!-- <a href="#">Following <span class="badge"><%#= User.find_by_id(current_user.id).following.count %></span></a> -->
    <button class="btn btn-info" type="button">Following <span class="badge"><%= link_to User.find_by_id(current_user.id).following.count, following_path(id: current_user.id) %></span></button>

    <% follower_cnt = 0 %>
    <% User.all.each do |x| %>
      <% if x.following.include?("id" => current_user.id.to_s) %>
            <% follower_cnt += 1 %>
      <% end %>
    <% end %>
    <!-- <p>Number of Followers: <%= follower_cnt %></p> -->
    <!-- <a href="#">Followers <span class="badge"><%= follower_cnt %></span></a> -->
    <button class="btn btn-info" type="button">Followers <span class="badge"><%= link_to follower_cnt, followers_path(id: current_user.id) %></span></button>
    <hr>
    <p>Here is what your "friends" are saying:</p>
  </div>

  <div class="container-fluid" style="font-family: 'Raleway', 'sans-serif'; font-size: 16px;">
    <div class="row">
      <div class="col-md-6 col-md-offset-4
                  col-sm-8 col-md-offset-2
                  col-xs-10 col-xs-offset-1">

        <div>
          <% @following_tweets.each do |tweet| %>
            <div class="well">
              <p>
                <%= image_tag tweet.user.avatar.url, class: 'user-pic-nav img-responsive' %>
                <%= link_to tweet.user.name, show_user_path(id: tweet.user_id) %>
                @<%= link_to tweet.user.username, show_user_path(id: tweet.user_id) %>
                <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
                <%= tweet.created_at.strftime('%b%e') if Time.now - tweet.created_at > 86400 %>
              </p>

              <p>
                <%= tweet.message.html_safe %>
              </p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/epicenter/followers.html.erb
<h2><%= @user.name %>'s Followers</h2>

<%= render 'user_list' %>

app/views/epicenter/following.html.erb
<h2><%= @user.name %> is following:</h2>

<%= render 'user_list' %>

app/views/epicenter/now_following.html.erb
<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<div class="container-fluid" style="font-family: 'Raleway', 'sans-serif'; font-size: 16px;">
    <div class="row">
      <div style="text-align: center;">
        <h1>@<%= @user.username %>'s Profile & Tweets</h1>

        <p>Name: <%= @user.name %></p>

        <% if !@user.location.empty? %>
          <p>Location: <%= @user.location %></p>
        <% end %>
        <% if !@user.bio.empty? %>
          <p>Bio: <%= @user.bio %></p>
        <% end %>

        <button class="btn btn-info" type="button">Tweets <span class="badge"><%= Tweet.all.where(:user_id => @user.id).count %></span></button>

        <button class="btn btn-info" type="button">Following <span class="badge"><%= link_to User.find_by_id(@user.id).following.count, following_path(id: @user.id) %></span></button>

        <% follower_cnt = 0 %>
        <% User.all.each do |x| %>
        <%  if x.following.include?("id" => @user.id.to_s) %>
                <% follower_cnt += 1 %>
            <% end %>
        <% end %>
        <button class="btn btn-info" type="button">Followers <span class="badge"><%= link_to follower_cnt, followers_path(id: @user.id) %></span></button>
        <br>
        <br>
        <p>
            <% if current_user.following.include?("id" => @user.id.to_s) %>
                <%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary", id: 'unfollow_btn' %>
            <% else %>
                <% if current_user.id != @user.id %>
                    <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-info" %>
                <% end %>
            <% end %>
        </p>

        <% @user.tweets.each do |tweet| %>
            <div>
                <p>@<%= @user.username %></p>
                <p><%= tweet.message %></p>
            </div>
        <% end %>

        <%= link_to 'Back', tweets_path, class: 'btn btn-primary' %>

      </div>
    </div>
</div>

app/views/epicenter/tag_tweets.html.erb
<div class="container-fluid">
  <div class="text-center">
    <h1><%= @tag.phrase %></h1>
  </div>

  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <% @tag.tweets.each do |tweet| %>
        <p style="text-align: center;">
          <!-- <%#= tweet.user.name %> <%#= "@#{tweet.user.username}" %> - <%= time_ago_in_words(tweet.created_at) %> ago -->
          <%= tweet.user.username %> - <%= time_ago_in_words(tweet.created_at) %> ago
        </p>

        <p style="text-align: center;">
          <%= tweet.message.html_safe %>
        </p>
        <br>
      <% end %>
    </div>

  </div>

</div>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/_header.html.erb
<div class="jumbotron" style="padding-top: 0; padding-bottom: 0; margin-bottom: 0;">
  <div style="color: white;
              background-image: url('https://cdn.pixabay.com/photo/2017/03/24/07/28/twitter-2170426_960_720.png');
              background-size: cover;
              background-position: center;
              height: 200px;
              padding: 20px;">
      <p id="notice"><%= notice %></p>
      <div class="pull-left" style="padding-left: 50px;">
        <i class="fa fa-twitter fa-2x" aria-hidden="true"></i>
      </div>

      <br>
      <div style="text-align: center; width: 100%;">
          <h2>What's Happening?</h2>
      </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" style="margin-bottom: 0;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Tweettastic!!</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to "Featured", tweets_path %></li>
          <li><%= link_to "My Feed", root_path %></li>
          <li><%= link_to 'New Tweet', new_tweet_path %></li>
          <li><%= link_to 'All Users', all_users_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><p class="navbar-text">Welcome back, <%= current_user.username %>!</p></li>
          <% if current_user.avatar.url %>
            <li><%= image_tag current_user.avatar.url, style: 'height: 50px;' %></li>
          <% end %>
          <li><%= link_to "Update Profile", edit_user_registration_path, class: 'btn btn-default' %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-default' %>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-info' %></li>
          <li><%= link_to "Log In", user_session_path, class: 'btn btn-success' %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTwitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/header' %>

    <%= yield %>
  </body>
</html>

app/views/tweets/_featured.html.erb
    <h2 style="text-align: center;">Featured Tweets</h2>
    <div class="container-fluid">
      <div class="row">

          <% @tweets.each do |tweet| %>

            <div class="col-lg-3 col-md-4 col-sm-8 col-xs-10">
              <div class="thumbnail" style="height: 242px; width: 300px;">

                  <p><%= tweet.message.html_safe %></p>
                  <p>Created by: <%= link_to tweet.user.username, show_user_path(id: tweet.user_id) %>
                    <%= time_ago_in_words(tweet.created_at, include_seconds: true) %> ago
                  </p>

                  <div class="caption" style="text-align: center; position: absolute; bottom: 20px; left: 60px;">
                    <%= link_to 'Show', tweet, class: 'btn btn-info' %>
                    <%= link_to 'Edit', edit_tweet_path(tweet), class: 'btn btn-warning' %>
                    <%= link_to 'Destroy', tweet, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
                  </div><!-- caption -->

                </div><!-- thumbnail -->
            </div><!-- col-md-3 -->
          <% end %>

      </div><!-- row -->

  </div><!-- container-fluid -->

app/views/tweets/_footer.html.erb
<!-- </div>

  <div class="container-fluid" style="padding-top: 10px; width: 100%; text-align: center; font-size: x-small;">
    <div class="footer">
      <ul>
        <li style="display: inline-block; padding: 0 9px 0 9px; text-align: inherit;">
          <a href="#">About</a>
        </li>
        <li style="display: inline-block; padding: 0 9px 0 9px; text-align: inherit;">
          <a href="#">Blog</a>
        </li>
        <li style="display: inline-block; padding: 0 9px 0 9px; text-align: inherit;">
          <a href="#">Help Center</a>
        </li>
        <li style="display: inline-block; padding: 0 9px 0 9px; text-align: inherit;">
          <a href="#">Status</a>
        </li>
        <li style="display: inline-block; padding: 0 9px 0 9px; text-align: inherit;">
          <a href="#">Jobs</a>
        </li>
        <li style="display: inline-block; padding: 0 9px 0 9px; text-align: inherit;">
          <a href="#">Terms</a>
        </li>
        <li style="display: inline-block; padding: 0 9px 0 9px; text-align: inherit;">
          <a href="#">Privacy Policy</a>
        </li>
        <li style="display: inline-block; padding: 0 9px 0 9px; text-align: inherit;">
          <a href="#">Cookies</a>
        </li>
        <li style="display: inline-block; padding: 0 9px 0 9px; text-align: inherit;">
          <a href="#">Ads info</a>
        </li>
        <li style="display: inline-block; padding: 0 9px 0 9px; text-align: inherit;">
          <a href="#">Brand</a>
        </li>
        <li style="display: inline-block; padding: 0 9px 0 9px; text-align: inherit;">
          <a href="#">Apps</a>
        </li>
        <li style="display: inline-block; padding: 0 9px 0 9px; text-align: inherit;">
          <a href="#">Advertise</a>
        </li>
        <li style="display: inline-block; padding: 0 9px 0 9px; text-align: inherit;">
          <a href="#">Businesses</a>
        </li>
        <li style="display: inline-block; padding: 0 9px 0 9px; text-align: inherit;">
          <a href="#">Developers</a>
        </li>
        <li style="display: inline-block; padding: 0 9px 0 9px; text-align: inherit;">
          <a href="#">Directory</a>
        </li>
        <li style="display: inline-block; padding: 0 9px 0 9px; text-align: inherit;">
          <a href="#">Settings</a>
        </li>

      </ul>

    </div>
    <a href="#">&copy;2017 Twitter</a>
  </div> -->


</div>

  <div class="container-fluid" style="padding-top: 10px; width: 100%; text-align: center; font-size: x-small;">
    <div class="footer">
      <ul>
        <li>
          <a href="#">About</a>
        </li>
        <li>
          <a href="#">Blog</a>
        </li>
        <li>
          <a href="#">Help Center</a>
        </li>
        <li>
          <a href="#">Status</a>
        </li>
        <li>
          <a href="#">Jobs</a>
        </li>
        <li>
          <a href="#">Terms</a>
        </li>
        <li>
          <a href="#">Privacy Policy</a>
        </li>
        <li>
          <a href="#">Cookies</a>
        </li>
        <li>
          <a href="#">Ads info</a>
        </li>
        <li>
          <a href="#">Brand</a>
        </li>
        <li>
          <a href="#">Apps</a>
        </li>
        <li>
          <a href="#">Advertise</a>
        </li>
        <li>
          <a href="#">Businesses</a>
        </li>
        <li>
          <a href="#">Developers</a>
        </li>
        <li>
          <a href="#">Directory</a>
        </li>
        <li>
          <a href="#">Settings</a>
        </li>

      </ul>

    </div>
    <a href="#">&copy;2017 Twitter</a>
  </div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message, id: :tweet_message %>
  </div>

  <div class="field">
    <!-- <%#= form.label :user_id %> -->
    <!-- to display username -->
    <%#= form.number_field :user_id, id: :tweet_user_id %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit "Tweet it!" %>
  </div>
<% end %>

app/views/tweets/_livefeed.html.erb
    <div class="col-md-8" style="padding-left: 120px;">
      <h4>Live video</h4>
    </div>

    <div class="container-fluid" style="padding: 0 100px 0 100px;">
      <div class="col">
        <div class="col-md-9">
          <iframe style="width: 100%; height: 300px; border-radius: 10px;"
            src="https://www.youtube.com/embed/m1i93VRK_RM">
          </iframe>
        </div>
        <div class="col-md-3" style="background-color: rgb(255, 100, 0);
                                    border-radius: 10px;
                                    text-align: center;
                                    height: 300px;
                                    color: white;
                                    line-height: 20px;">
          <div style="margin-top: 70px;">
            <h3>New to Twitter?</h3>
          </div>
          <div style="font-size: 14px; letter-spacing: .5px;">
            <p>Sign up now to get your own personalized timeline!</p>
          </div>
          <div>

          </div>
            <a href="https://twitter.com/signup"><button type="button" class="btn btn-default">Sign Up</button></a>
          </div>
        </div>
      </div>
    </div>

app/views/tweets/edit.html.erb
<div class="container-fluid" style="font-family: 'Raleway', 'sans-serif'; font-size: 16px;">
    <div class="row">
      <div class="col-md-6 col-md-offset-5
                  col-sm-8 col-md-offset-2
                  col-xs-10 col-xs-offset-1">


        <h1>Editing Tweet</h1>

        <%= render 'form', tweet: @tweet %>

        <br>
        <%= link_to 'Show', @tweet, class: 'btn btn-primary' %>
        <%= link_to 'Back', tweets_path, class: 'btn btn-primary' %>

      </div>
    </div>
</div>

app/views/tweets/index.html.erb
<%#= render 'tweets/header' %>
<%= render 'tweets/navbar' %>
<%= render 'tweets/livefeed' %>
<%= render 'tweets/featured' %>


<!-- All from here is original -->
<!-- <p id="notice"><%= notice %></p> -->
<!-- <h1>Tweets</h1> -->

<h2 style="text-align: center;">Table of Tweets</h2>
<div class="panel panel-default" style="padding-left: 20px; padding-right: 20px; padding-top: 20px;">
  <!-- Default panel contents -->
  <div class="panel-heading">

    <table class="table table-striped table-hover well well-lg">
      <thead>
        <tr>
          <th>Message</th>
          <th>User</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @tweets.each do |tweet| %>
          <tr>
            <td><%= tweet.message.html_safe %></td>
            <!-- <td><%= tweet.user.username %></td> -->
            <td><%= link_to tweet.user.username, show_user_path(id: tweet.user_id) %></td>
            <td><%= link_to 'Show', tweet, class: 'btn btn-info' %></td>
            <td><%= link_to 'Edit', edit_tweet_path(tweet), class: 'btn btn-warning' %></td>
            <td><%= link_to 'Destroy', tweet, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
  <br>

<%#= link_to 'New Tweet', new_tweet_path, class: 'btn btn-primary' %>

  <%= render 'tweets/footer' %>
</div>

app/views/tweets/new.html.erb
<div class="container-fluid" style="font-family: 'Raleway', 'sans-serif'; font-size: 16px;">
    <div class="row">
      <div class="col-md-6 col-md-offset-5
                  col-sm-8 col-md-offset-2
                  col-xs-10 col-xs-offset-1">

        <h1>New Tweet</h1>

        <%= render 'form', tweet: @tweet %>

        <%= link_to 'Back', tweets_path, class: "btn btn-primary navbar-btn" %>
      </div>
    </div>
</div>

app/views/tweets/show.html.erb
<div class="container-fluid" style="font-family: 'Raleway', 'sans-serif'; font-size: 16px;">
    <div class="row">
      <div style="text-align: center;">

        <p id="notice"><%= notice %></p>

        <h1>View or Update Tweet</h1>
        <p>
          <strong>Message:</strong>
          <%= @tweet.message.html_safe %>
        </p>

        <p>
          <strong>Created: </strong>
          <%= time_ago_in_words(@tweet.created_at, include_seconds: true) %> ago
        </p>

        <p>
          <strong>User:</strong>
          <%#= @tweet.user_id %>
          <%= link_to @tweet.user.username, show_user_path(id: @tweet.user_id) %>
        </p>

        <%= link_to 'Edit', edit_tweet_path(@tweet), class: 'btn btn-primary' %>
        <%= link_to 'Back', tweets_path, class: 'btn btn-primary' %>

      </div>
    </div>
</div>